services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - nats_data:/data
    command:
      - --jetstream
      - --http_port=8222

volumes:
  nats_data: